learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('49b0e624-74ae-40b1-bf3b-057f16f24289/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
"""Определяет схемы URL для laerning_logs"""

from django.urls import path
from . import views


app_name = 'learning_logs'
urlpatterns = [
    # Домашняя страница
    path('', views.index, name='index'),
    # Страница со списком всех тем
    path('topics/', views.topics, name='topics'),
    # Страница с подробной информацией по отдельной теме
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Страница для добавления новой темы
    path('new_topic/', views.new_topic, name='new_topic'),
    # Страница для добавления новой записи
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Страница для редактирования записи
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
    # Удаление записи
    path('delete_entry/<int:entry_id>', views.delete_entry, name='delete_entry'),
    # Удаление темы
    path('delete_topic/<int:topic_id>', views.delete_topic, name='delete_topic'),
]

users/urls.py
"""Определяет схемы URL для пользователей"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Включить URL авторизации по умолчанию
    path('', include('django.contrib.auth.urls')),
    # Страница регистрации
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
	"""Тема, которую изучает пользователь."""
	text = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		"""Возвращает строковое представление модели."""
		return self.text


class Entry(models.Model):
	"""Информация, изученная пользователем по теме."""
	topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = 'entries'

	def __str__(self):
		"""Возвращает строковое представление модели."""
		if len(self.text) > 50:
			return f"{self.text[:50]}..."
		else:
			return self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}

learning_logs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topic, Entry
from .forms import TopicForm, EntryForm


def index(request):
    """Домашняя страница приложения learning_log"""
    return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
    """Выводит список тем"""
    if request.user.username == 'admin':
        topics = Topic.objects.all()
    else:
        topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    """Выводит одну тему и все ее записи"""
    topic = get_object_or_404(Topic, pk=topic_id)
    check_topic_owner(request, topic)

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    """Определяет новую тему"""
    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма
        form = TopicForm()
    else:
        # Отправлены данные POST; обработать данные
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')

    # Вывести пустую или недействительную форму
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


def delete_topic(request, topic_id):
    """Удаляет существующую тему"""
    topic = get_object_or_404(Topic, pk=topic_id)
    check_topic_owner(request, topic)

    topic.delete()
    return redirect('learning_logs:topics')


@login_required
def new_entry(request, topic_id):
    """Добавляет новую запись по конкретной теме"""
    topic = get_object_or_404(Topic, pk=topic_id)
    check_topic_owner(request, topic)
    if request.method != 'POST':
        # Данные не отправлялись, создается пустая форма
        form = EntryForm()
    else:
        # Отправлены данные POST; обработать данные
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)

    # Вывести пустую или недействительную форму
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """Редактирует существующую запись"""
    entry = get_object_or_404(Entry, pk=entry_id)
    topic = entry.topic
    check_topic_owner(request, topic)

    if request.method != 'POST':
        # Исходный запрос; форма заполняется данными текущей записи
        form = EntryForm(instance=entry)
    else:
        # Отправка данных POST; обработать данные
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


@login_required
def delete_entry(request, entry_id):
    """Удаляет существующую запись"""
    entry = get_object_or_404(Entry, pk=entry_id)
    topic = entry.topic
    check_topic_owner(request, topic)

    entry.delete()
    return redirect('learning_logs:topic', topic_id=topic.id)


def check_topic_owner(request, topic):
    """Проверяет связь между пользователем и темой"""
    if topic.owner != request.user and request.user.username != 'admin':
        raise Http404

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """Регистрирует нового пользователя"""
    if request.method != 'POST':
        # Выводит пустую форму регистрации
        form = UserCreationForm()
    else:
        # Обработка заполненной формы
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Выполнение входа и перенаправление на домашнюю страницу
            login(request, new_user)
            return redirect('learning_logs:index')

    # Вывести пустую или недействительную форму
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Learning Log</title>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'learning_logs:topics' %}">Topics</a>
          </li>
        </ul>
        {% if user.is_authenticated %}
          <span class="navbar-text">
            Hello, {{ user.username }}
          </span>
          <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
        {% endif %}
      </div>
    </div>
  </nav>

  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}
      {% endblock page_header %}
    </div>
    <div>
      {% block content %}
      {% endblock content %}
    </div>
  </main>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>

</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}


{% block page_header %}
  <h3><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3>
{% endblock page_header %}

{% block content %}
  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post" class="form">
    {% csrf_token %}
    <div class=" mb-3">
      <label for="id_text" class="form-label">Entry:</label>
      <textarea class="form-control" name="text" maxlength="1000" rows="10" required id="id_text">{{ entry.text }}</textarea>
    </div>
    <button name="submit" class="btn btn-primary">Save changes</button>
    <input type="hidden" name="next" value="{% url 'learning_logs:topic' topic.id%}">
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}


{% block page_header %}
  <div class="jumbotron">
    <h1 class="display-3">Track your learning.</h1>
    <p class="lead">Make your own Learning Log,
      and keep a list of the topics you're learning about.
      Whenever you learn something new about a topic,
      make an entry summarizing what you've learned.</p>
    {% if user.is_authenticated %}
    {% else %}
      <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">Register</a>
      <a class="btn btn-lg btn-primary" href="{% url 'users:login' %}" role="button">Log in</a>
    {% endif %}
  </div>
{% endblock page_header %}

{% block content %}
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}


{% block page_header %}
  <h3><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3>
{% endblock page_header %}

{% block content %}
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post" class="form">
    {% csrf_token %}
    <div class=" mb-3">
      <label for="id_text" class="form-label">Entry:</label>
      <textarea class="form-control" name="text" maxlength="1000" rows="10" required id="id_text"></textarea>
    </div>
    <button name="submit" class="btn btn-primary">Add entry</button>
    <input type="hidden" name="next" value="{% url 'learning_logs:topic' topic.id%}">
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}


{% block page_header %}
  <h3>Add a new topic</h3>
{% endblock page_header %}

{% block content %}
  <form action="{% url 'learning_logs:new_topic' %}" method="post" class="form">
    {% csrf_token %}
    <div class=" mb-3">
      <input class="form-control" type="text" name="text" maxlength="100" required id="id_text">
    </div>
    <button name="submit" class="btn btn-primary">Add topic</button>
    <input type="hidden" name="next" value="{% url 'learning_logs:topics' %}">
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}


{% block page_header %}
  <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}
  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#new_entry"><i class="fa fa-plus" aria-hidden="true"></i> Add new entry</button>
  <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#delete_topic"><i class="fa fa-trash-o" aria-hidden="true"></i> Delete topic</button>
  <p></p>
  {% for entry in entries %}
    <div class="card mb-3">
      <h4 class="card-header">
        {{ entry.date_added|date:'M d, Y H:i' }}<br>
        <button type="button" class="btn btn-secondary btn-sm" data-bs-toggle="modal" data-bs-target="#edit_entry_{{ entry.id }}"><i class="fa fa-pencil" aria-hidden="true"></i> Edit entry</button>
        <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#delete_entry_{{ entry.id }}"><i class="fa fa-trash-o" aria-hidden="true"></i> Delete entry</button>
      </h4>
      <div class="card-body">
        {{ entry.text|linebreaks }}
      </div>
    </div>

    <div class="modal fade" id="edit_entry_{{ entry.id }}" tabindex="-1" aria-labelledby="edit_entryLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="edit_entryLabel">Edit entry</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <form id='form_edit_entry' action="{% url 'learning_logs:edit_entry' entry.id %}" method="post" class="form">
              {% csrf_token %}
              <div class=" mb-3">
                <label for="id_text" class="form-label">Entry:</label>
                <textarea class="form-control" name="text" maxlength="1000" rows="10" required id="id_text">{{ entry.text }}</textarea>
              </div>
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button form='form_edit_entry' name="submit" class="btn btn-primary"> Save changes</button>
            <input form='form_edit_entry' type="hidden" name="next" value="{% url 'learning_logs:topic' topic.id%}">
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade" id="delete_entry_{{ entry.id }}" tabindex="-1" aria-labelledby="delete_entryLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="delete_entryLabel">Delete entry</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <p>Are you sure?</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <a class="btn btn-danger" href="{% url 'learning_logs:delete_entry' entry.id %}" role="button"><i class="fa fa-trash-o" aria-hidden="true"></i> Delete entry</a>
          </div>
        </div>
      </div>
    </div>
  {% empty %}
    <p>There are no entries for this topic yet.</p>
  {% endfor %}
  <div class="modal fade" id="new_entry" tabindex="-1" aria-labelledby="new_entryLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="new_entryLabel">New entry</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form id='form_new_entry' action="{% url 'learning_logs:new_entry' topic.id %}" method="post" class="form">
            {% csrf_token %}
            <div class=" mb-3">
              <label for="id_text" class="form-label">Entry:</label>
              <textarea class="form-control" name="text" maxlength="1000" rows="10" required id="id_text"></textarea>
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button form='form_new_entry' name="submit" class="btn btn-primary"><i class="fa fa-plus" aria-hidden="true"></i> Add entry</button>
          <input form='form_new_entry' type="hidden" name="next" value="{% url 'learning_logs:topic' topic.id%}">
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="delete_topic" tabindex="-1" aria-labelledby="delete_topicLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="delete_topicLabel">Delete topic</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>Are you sure?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <a class="btn btn-danger" href="{% url 'learning_logs:delete_topic' topic.id %}" role="button"><i class="fa fa-trash-o" aria-hidden="true"></i> Delete</a>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}


{% block page_header %}
  <h1>Topics</h1>
{% endblock page_header %}

{% block content %}
  <ul>
    {% for topic in topics %}
      <li><h3>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
      </h3></li>
    {% empty %}
      <li><h3>No topics have been added yet.</h3></li>
    {% endfor %}
  </ul>
  <h3><a class="btn btn-primary" href="{% url 'learning_logs:new_topic' %}" role="button"><i class="fa fa-plus" aria-hidden="true"></i> Add new topic</a></h3>
{% endblock content %}